### ISSUE TITLE
Cual es el procedimiento si el Wallet esta hecho en Flutter/Dart y no en Javascript?

### ISSUE THREAD

**Issue by jesus-alastria** [alastria/alastria-identity-JSON-objects#12]
No se especifica el procedimiento si el Wallet esta construido en un lenguaje diferente a Javascript, por ejemplo en Flutter/Dart.
¿Como se debe realizar la prueba en esos casos?

**Comment by nmanero** [comment]
En este caso, la idea era dejar las credenciales, presentaciones... en ficheros json dentro de la carpeta del vendor correspondiente.
En el caso que comentas, ¿dónde estarían estos valores que quieres validar si cumplen con el modelo?
