### ISSUE TITLE
 Check if hexadecimal fields start with "0x"

### ISSUE THREAD

**Issue by VictorNS69** [alastria/alastria-identity-JSON-objects#17]
Check every hexadecimal field (public keys, transactions, etc)

- [x] Alastria Identity Creation (AIC)
- [x] Alastria Session
- [x] Presentation Request
- [x] Presentation
- [x] Credentials

**Comment by nmanero** [comment]
Done with Credendials and tokens. Branch used https://github.com/alastria/alastria-identity-JSON-objects/tree/feature/17-force-0x-in-hexadecimal

**Comment by nmanero** [comment]
About this task, I have two questions related to Sessions and Alastria Id Creation:
In Sessions, in JSON schema, in property PKU, 0x is not required, is it an hex value or just a string?
In Alastria Id Creation the same with createAlastriaTX and publicKey properties. Are hex or string values?
@jotafernandez @Saithan16

**Comment by Saithan16** [comment]
After what @VictorNS69 said in #4 about the PKU in Session, '0x' is mandatory, but we forgot to change it afterwards in the schema, sorry.
I guess the same thing should apply in AlastriaIdCreation, at least for 'createAlastriaTx', but for the 'publicKey', the example in #3 doesn't have '0x', but it does in the wiki (https://github.com/alastria/alastria-identity/wiki/Actions-and-Objects-Definition#03-alastria-id-creation-aic) so... idk

**Comment by msalitu** [comment]
Hello, I think that the consensus after the last meeting was to have '0x' mandatory in all hex values just with one exception which is the final part of the DID (it is the Alastria Proxy address but without '0x'). If you find any contradiction in the documentation, please, let me know

**Comment by jotafernandez** [comment]
@nmanero The schemes are already modified to admit the 0x pattern as mandatory.

**Comment by DrankoLQ** [comment]
Looks like its already done, so I'm gonna close it 🤓
