### ISSUE TITLE
U2 - presentation

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-JSON-objects#25]
Adaptar a los cambios de https://github.com/alastria/alastria-identity-lib/issues/70

El jwk del header debe ser opcional

**Comment by msalitu** [comment]
Eliminar la restricción del numero 1 en el kid, puede ser cualquier entero

**Comment by carlosalvarezrivas** [comment]
# Pruebas Test U2-Presentations

## 1 - Introducción

El motivo de este documento es plasmar las pruebas realizadas de los JSON Objets Presentations del modelo DID Alastria.



## 2 - Pruebas JSON Objets Presentations

Las pruebas han consistido en ir testeando distintos JSON en la librería de pruebas. 

La primera prueba ha consistido en un JSON válido y el resto en JSON con distintos errores según los elementos necesarios en el objeto.

La librería de  pruebas que se ha utilizado ha sido:

https://github.com/alastria/alastria-identity-JSON-objects



### 2.1 - Prueba JSON válido

**Ejemplo presentation sin codificar:**

`{`
`header: {`
`{`
  `"typ": "JWT",`
  `"alg": "ES256K",`
  `"kid": "did:ala:quor:redT:9117e39d3870185910a61af3c707f6333104ff14#keys-1",`
  `"jwk": "0x2e507af01167c98a6accc0cd46ab2a256dd6b6c69ec1c0c28f80fb62e1f7d70233768b0c58dbbdac1fc358b8141c075a520483cf9779e4ea98d13df2833f3767"`
`},`
`payload: {`
  `"jti": "https://www.empresa.com/alastria/credentials/3734",`
  `"iss": "did:ala:quor:redT:9117e39d3870185910a61af3c707f6333104ff14",`
  `"aud": "did:ala:quor:redT:00f471c75c14c9ee9b16e4d64f8acb47a7bf2c4a",`
  `"iat": 1588160378,`
  `"exp": 1563783392,`
  `"nbf": 1563782792,`
  `"vp": {`
    `"@context": [`
           `"https://www.w3.org/2018/credentials/v1",`
           `"https://alastria.github.io/identity/credentials/v1"`
    `],`
    `"type": [`
      `"VerifiablePresentation","AlastriaVerifiablePresentation"`
    `],`
    `"procUrl": "https://www.empresa.com/alastria/businessprocess/4583",`
    `"procHash": "H398sjHd...kldjUYn475n",`
    `"verifiableCredential": [`
`"eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksiLCJraWQiOiJkaWQ6YWxhOnF1b3I6cmVkVDowMGY0NzFjNzVjMTRjOWVlOWIxNmU0ZDY0ZjhhY2I0N2E3YmYyYzRhIn0.eyJqdGkiOiJodHRwczovL3d3dy5lbXByZXNhLmNvbS9hbGFzdHJpYS9jcmVkZW50aWFscy8zNzM0IiwiaXNzIjoiZGlkOmFsYTpxdW9yOnJlZFQ6MDBmNDcxYzc1YzE0YzllZTliMTZlNGQ2NGY4YWNiNDdhN2JmMmM0YSIsInN1YiI6ImRpZDphbGE6cXVvcjpyZWRUOjkxMTdlMzlkMzg3MDE4NTkxMGE2MWFmM2M3MDdmNjMzMzEwNGZmMTQiLCJpYXQiOjE1ODgxNjAzNjEsImV4cCI6MTU2Mzc4MzM5MiwibmJmIjoxNTYzNzgyNzkyLCJ2YyI6eyJAY29udGV4dCI6Imh0dHBzOi8vdzNpZC5vcmcvZGlkL3YxIiwidHlwZSI6WyJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsIkFsYXN0cmlhRXhhbXBsZUNyZWRlbnRpYWwiXSwiY3JlZGVudGlhbFN1YmplY3QiOnsibGV2ZWxPZkFzc3VyYW5jZSI6ImJhc2ljIiwiZG5pX251bWVybyI6IjAwMDAwMDQxSCJ9fX0.TAXqGDsxSwOJB5nBzoIoFRStOFb4HTJH3OOujcs5NCySjswa0mI0R5q3aqqsB4A9monOEB1VpH2TulBW615Kcg"`
    `]`
  `}`
`}`
`}`



**Ejemplo presentation codificada:**

`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRpZDphbGE6cXVvcjpyZWRUOjkxMTdlMzlkMzg3MDE4NTkxMGE2MWFmM2M3MDdmNjMzMzEwNGZmMTQja2V5cy0xIiwiandrIjoiMHgyZTUwN2FmMDExNjdjOThhNmFjY2MwY2Q0NmFiMmEyNTZkZDZiNmM2OWVjMWMwYzI4ZjgwZmI2MmUxZjdkNzAyMzM3NjhiMGM1OGRiYmRhYzFmYzM1OGI4MTQxYzA3NWE1MjA0ODNjZjk3NzllNGVhOThkMTNkZjI4MzNmMzc2NyJ9.eyJqdGkiOiJodHRwczovL3d3dy5lbXByZXNhLmNvbS9hbGFzdHJpYS9jcmVkZW50aWFscy8zNzM0IiwiaXNzIjoiZGlkOmFsYTpxdW9yOnJlZFQ6OTExN2UzOWQzODcwMTg1OTEwYTYxYWYzYzcwN2Y2MzMzMTA0ZmYxNCIsImF1ZCI6ImRpZDphbGE6cXVvcjpyZWRUOjAwZjQ3MWM3NWMxNGM5ZWU5YjE2ZTRkNjRmOGFjYjQ3YTdiZjJjNGEiLCJpYXQiOjE1ODgxNjAzNzgsImV4cCI6MTU2Mzc4MzM5MiwibmJmIjoxNTYzNzgyNzkyLCJ2cCI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsImh0dHBzOi8vYWxhc3RyaWEuZ2l0aHViLmlvL2lkZW50aXR5L2NyZWRlbnRpYWxzL3YxIl0sInR5cGUiOlsiVmVyaWZpYWJsZVByZXNlbnRhdGlvbiIsIkFsYXN0cmlhVmVyaWZpYWJsZVByZXNlbnRhdGlvbiJdLCJwcm9jVXJsIjoiaHR0cHM6Ly93d3cuZW1wcmVzYS5jb20vYWxhc3RyaWEvYnVzaW5lc3Nwcm9jZXNzLzQ1ODMiLCJwcm9jSGFzaCI6IkgzOThzakhkLi4ua2xkalVZbjQ3NW4iLCJ2ZXJpZmlhYmxlQ3JlZGVudGlhbCI6WyJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpGVXpJMU5rc2lMQ0pyYVdRaU9pSmthV1E2WVd4aE9uRjFiM0k2Y21Wa1ZEb3dNR1kwTnpGak56VmpNVFJqT1dWbE9XSXhObVUwWkRZMFpqaGhZMkkwTjJFM1ltWXlZelJoSW4wLmV5SnFkR2tpT2lKb2RIUndjem92TDNkM2R5NWxiWEJ5WlhOaExtTnZiUzloYkdGemRISnBZUzlqY21Wa1pXNTBhV0ZzY3k4ek56TTBJaXdpYVhOeklqb2laR2xrT21Gc1lUcHhkVzl5T25KbFpGUTZNREJtTkRjeFl6YzFZekUwWXpsbFpUbGlNVFpsTkdRMk5HWTRZV05pTkRkaE4ySm1NbU0wWVNJc0luTjFZaUk2SW1ScFpEcGhiR0U2Y1hWdmNqcHlaV1JVT2preE1UZGxNemxrTXpnM01ERTROVGt4TUdFMk1XRm1NMk0zTURkbU5qTXpNekV3TkdabU1UUWlMQ0pwWVhRaU9qRTFPRGd4TmpBek5qRXNJbVY0Y0NJNk1UVTJNemM0TXpNNU1pd2libUptSWpveE5UWXpOemd5TnpreUxDSjJZeUk2ZXlKQVkyOXVkR1Y0ZENJNkltaDBkSEJ6T2k4dmR6TnBaQzV2Y21jdlpHbGtMM1l4SWl3aWRIbHdaU0k2V3lKV1pYSnBabWxoWW14bFEzSmxaR1Z1ZEdsaGJDSXNJa0ZzWVhOMGNtbGhSWGhoYlhCc1pVTnlaV1JsYm5ScFlXd2lYU3dpWTNKbFpHVnVkR2xoYkZOMVltcGxZM1FpT25zaWJHVjJaV3hQWmtGemMzVnlZVzVqWlNJNkltSmhjMmxqSWl3aVpHNXBYMjUxYldWeWJ5STZJakF3TURBd01EUXhTQ0o5ZlgwLlRBWHFHRHN4U3dPSkI1bkJ6b0lvRlJTdE9GYjRIVEpIM09PdWpjczVOQ3lTanN3YTBtSTBSNXEzYXFxc0I0QTltb25PRUIxVnBIMlR1bEJXNjE1S2NnIl19fQ.gUQ35MfofF4BnIzY3pM-oPg5Irc8kMlhBp3VITKQArw`



**Resultado test:**

![](https://www.lacometanetwork.com/ficheros/alastria/did/U2-presentations-todo-bien.png)



### 2.2 - Error JSON en objeto vp - @context

**Ejemplo presentation sin codificar:**
No añadimos en @context el item "https://alastria.github.io/identity/credentials/v1".

`{`
`header: {`
`{`
  `"typ": "JWT",`
  `"alg": "ES256K",`
  `"kid": "did:ala:quor:redT:9117e39d3870185910a61af3c707f6333104ff14#keys-1",`
  `"jwk": "0x2e507af01167c98a6accc0cd46ab2a256dd6b6c69ec1c0c28f80fb62e1f7d70233768b0c58dbbdac1fc358b8141c075a520483cf9779e4ea98d13df2833f3767"`
`},`
`payload: {`
  `"jti": "https://www.empresa.com/alastria/credentials/3734",`
  `"iss": "did:ala:quor:redT:9117e39d3870185910a61af3c707f6333104ff14",`
  `"aud": "did:ala:quor:redT:00f471c75c14c9ee9b16e4d64f8acb47a7bf2c4a",`
  `"iat": 1588160378,`
  `"exp": 1563783392,`
  `"nbf": 1563782792,`
  `"vp": {`
    `"@context": [`
           `"https://www.w3.org/2018/credentials/v1"`
    `],`
    `"type": [`
      `"VerifiablePresentation","AlastriaVerifiablePresentation"`
    `],`
    `"procUrl": "https://www.empresa.com/alastria/businessprocess/4583",`
    `"procHash": "H398sjHd...kldjUYn475n",`
    `"verifiableCredential": [`
`"eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksiLCJraWQiOiJkaWQ6YWxhOnF1b3I6cmVkVDowMGY0NzFjNzVjMTRjOWVlOWIxNmU0ZDY0ZjhhY2I0N2E3YmYyYzRhIn0.eyJqdGkiOiJodHRwczovL3d3dy5lbXByZXNhLmNvbS9hbGFzdHJpYS9jcmVkZW50aWFscy8zNzM0IiwiaXNzIjoiZGlkOmFsYTpxdW9yOnJlZFQ6MDBmNDcxYzc1YzE0YzllZTliMTZlNGQ2NGY4YWNiNDdhN2JmMmM0YSIsInN1YiI6ImRpZDphbGE6cXVvcjpyZWRUOjkxMTdlMzlkMzg3MDE4NTkxMGE2MWFmM2M3MDdmNjMzMzEwNGZmMTQiLCJpYXQiOjE1ODgxNjAzNjEsImV4cCI6MTU2Mzc4MzM5MiwibmJmIjoxNTYzNzgyNzkyLCJ2YyI6eyJAY29udGV4dCI6Imh0dHBzOi8vdzNpZC5vcmcvZGlkL3YxIiwidHlwZSI6WyJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsIkFsYXN0cmlhRXhhbXBsZUNyZWRlbnRpYWwiXSwiY3JlZGVudGlhbFN1YmplY3QiOnsibGV2ZWxPZkFzc3VyYW5jZSI6ImJhc2ljIiwiZG5pX251bWVybyI6IjAwMDAwMDQxSCJ9fX0.TAXqGDsxSwOJB5nBzoIoFRStOFb4HTJH3OOujcs5NCySjswa0mI0R5q3aqqsB4A9monOEB1VpH2TulBW615Kcg"`
    `]`
  `}`
`}`
`}`



**Ejemplo presentation codificada:**

`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRpZDphbGE6cXVvcjpyZWRUOjkxMTdlMzlkMzg3MDE4NTkxMGE2MWFmM2M3MDdmNjMzMzEwNGZmMTQja2V5cy0xIiwiandrIjoiMHgyZTUwN2FmMDExNjdjOThhNmFjY2MwY2Q0NmFiMmEyNTZkZDZiNmM2OWVjMWMwYzI4ZjgwZmI2MmUxZjdkNzAyMzM3NjhiMGM1OGRiYmRhYzFmYzM1OGI4MTQxYzA3NWE1MjA0ODNjZjk3NzllNGVhOThkMTNkZjI4MzNmMzc2NyJ9.eyJqdGkiOiJodHRwczovL3d3dy5lbXByZXNhLmNvbS9hbGFzdHJpYS9jcmVkZW50aWFscy8zNzM0IiwiaXNzIjoiZGlkOmFsYTpxdW9yOnJlZFQ6OTExN2UzOWQzODcwMTg1OTEwYTYxYWYzYzcwN2Y2MzMzMTA0ZmYxNCIsImF1ZCI6ImRpZDphbGE6cXVvcjpyZWRUOjAwZjQ3MWM3NWMxNGM5ZWU5YjE2ZTRkNjRmOGFjYjQ3YTdiZjJjNGEiLCJpYXQiOjE1ODgxNjAzNzgsImV4cCI6MTU2Mzc4MzM5MiwibmJmIjoxNTYzNzgyNzkyLCJ2cCI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSJdLCJ0eXBlIjpbIlZlcmlmaWFibGVQcmVzZW50YXRpb24iLCJBbGFzdHJpYVZlcmlmaWFibGVQcmVzZW50YXRpb24iXSwicHJvY1VybCI6Imh0dHBzOi8vd3d3LmVtcHJlc2EuY29tL2FsYXN0cmlhL2J1c2luZXNzcHJvY2Vzcy80NTgzIiwicHJvY0hhc2giOiJIMzk4c2pIZC4uLmtsZGpVWW40NzVuIiwidmVyaWZpYWJsZUNyZWRlbnRpYWwiOlsiZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKRlV6STFOa3NpTENKcmFXUWlPaUprYVdRNllXeGhPbkYxYjNJNmNtVmtWRG93TUdZME56RmpOelZqTVRSak9XVmxPV0l4Tm1VMFpEWTBaamhoWTJJME4yRTNZbVl5WXpSaEluMC5leUpxZEdraU9pSm9kSFJ3Y3pvdkwzZDNkeTVsYlhCeVpYTmhMbU52YlM5aGJHRnpkSEpwWVM5amNtVmtaVzUwYVdGc2N5OHpOek0wSWl3aWFYTnpJam9pWkdsa09tRnNZVHB4ZFc5eU9uSmxaRlE2TURCbU5EY3hZemMxWXpFMFl6bGxaVGxpTVRabE5HUTJOR1k0WVdOaU5EZGhOMkptTW1NMFlTSXNJbk4xWWlJNkltUnBaRHBoYkdFNmNYVnZjanB5WldSVU9qa3hNVGRsTXpsa016ZzNNREU0TlRreE1HRTJNV0ZtTTJNM01EZG1Oak16TXpFd05HWm1NVFFpTENKcFlYUWlPakUxT0RneE5qQXpOakVzSW1WNGNDSTZNVFUyTXpjNE16TTVNaXdpYm1KbUlqb3hOVFl6TnpneU56a3lMQ0oyWXlJNmV5SkFZMjl1ZEdWNGRDSTZJbWgwZEhCek9pOHZkek5wWkM1dmNtY3ZaR2xrTDNZeElpd2lkSGx3WlNJNld5SldaWEpwWm1saFlteGxRM0psWkdWdWRHbGhiQ0lzSWtGc1lYTjBjbWxoUlhoaGJYQnNaVU55WldSbGJuUnBZV3dpWFN3aVkzSmxaR1Z1ZEdsaGJGTjFZbXBsWTNRaU9uc2liR1YyWld4UFprRnpjM1Z5WVc1alpTSTZJbUpoYzJsaklpd2laRzVwWDI1MWJXVnlieUk2SWpBd01EQXdNRFF4U0NKOWZYMC5UQVhxR0RzeFN3T0pCNW5Cem9Jb0ZSU3RPRmI0SFRKSDNPT3VqY3M1TkN5U2pzd2EwbUkwUjVxM2FxcXNCNEE5bW9uT0VCMVZwSDJUdWxCVzYxNUtjZyJdfX0.oNTh3sBQBftzoNY6VMqZyxuFTWkbMa5z4NWJWpjL2Sw`



**Resultado test:**

![](https://www.lacometanetwork.com/ficheros/alastria/did/U2-presentations-error-context.png)





### 2.3 - Error JSON en objeto vp - type

**Ejemplo presentation sin codificar:**
No añadimos en type el item "AlastriaVerifiablePresentation".

`{`
`header: {`
`{`
  `"typ": "JWT",`
  `"alg": "ES256K",`
  `"kid": "did:ala:quor:redT:9117e39d3870185910a61af3c707f6333104ff14#keys-1",`
  `"jwk": "0x2e507af01167c98a6accc0cd46ab2a256dd6b6c69ec1c0c28f80fb62e1f7d70233768b0c58dbbdac1fc358b8141c075a520483cf9779e4ea98d13df2833f3767"`
`},`
`payload: {`
  `"jti": "https://www.empresa.com/alastria/credentials/3734",`
  `"iss": "did:ala:quor:redT:9117e39d3870185910a61af3c707f6333104ff14",`
  `"aud": "did:ala:quor:redT:00f471c75c14c9ee9b16e4d64f8acb47a7bf2c4a",`
  `"iat": 1588160378,`
  `"exp": 1563783392,`
  `"nbf": 1563782792,`
  `"vp": {`
    `"@context": [`
           `"https://www.w3.org/2018/credentials/v1",`
           `"https://alastria.github.io/identity/credentials/v1"`
    `],`
    `"type": [`
      `"VerifiablePresentation"`
    `],`
    `"procUrl": "https://www.empresa.com/alastria/businessprocess/4583",`
    `"procHash": "H398sjHd...kldjUYn475n",`
    `"verifiableCredential": [`
`"eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksiLCJraWQiOiJkaWQ6YWxhOnF1b3I6cmVkVDowMGY0NzFjNzVjMTRjOWVlOWIxNmU0ZDY0ZjhhY2I0N2E3YmYyYzRhIn0.eyJqdGkiOiJodHRwczovL3d3dy5lbXByZXNhLmNvbS9hbGFzdHJpYS9jcmVkZW50aWFscy8zNzM0IiwiaXNzIjoiZGlkOmFsYTpxdW9yOnJlZFQ6MDBmNDcxYzc1YzE0YzllZTliMTZlNGQ2NGY4YWNiNDdhN2JmMmM0YSIsInN1YiI6ImRpZDphbGE6cXVvcjpyZWRUOjkxMTdlMzlkMzg3MDE4NTkxMGE2MWFmM2M3MDdmNjMzMzEwNGZmMTQiLCJpYXQiOjE1ODgxNjAzNjEsImV4cCI6MTU2Mzc4MzM5MiwibmJmIjoxNTYzNzgyNzkyLCJ2YyI6eyJAY29udGV4dCI6Imh0dHBzOi8vdzNpZC5vcmcvZGlkL3YxIiwidHlwZSI6WyJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsIkFsYXN0cmlhRXhhbXBsZUNyZWRlbnRpYWwiXSwiY3JlZGVudGlhbFN1YmplY3QiOnsibGV2ZWxPZkFzc3VyYW5jZSI6ImJhc2ljIiwiZG5pX251bWVybyI6IjAwMDAwMDQxSCJ9fX0.TAXqGDsxSwOJB5nBzoIoFRStOFb4HTJH3OOujcs5NCySjswa0mI0R5q3aqqsB4A9monOEB1VpH2TulBW615Kcg"`
    `]`
  `}`
`}`
`}`



**Ejemplo presentation codificada:**

`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRpZDphbGE6cXVvcjpyZWRUOjkxMTdlMzlkMzg3MDE4NTkxMGE2MWFmM2M3MDdmNjMzMzEwNGZmMTQja2V5cy0xIiwiandrIjoiMHgyZTUwN2FmMDExNjdjOThhNmFjY2MwY2Q0NmFiMmEyNTZkZDZiNmM2OWVjMWMwYzI4ZjgwZmI2MmUxZjdkNzAyMzM3NjhiMGM1OGRiYmRhYzFmYzM1OGI4MTQxYzA3NWE1MjA0ODNjZjk3NzllNGVhOThkMTNkZjI4MzNmMzc2NyJ9.eyJqdGkiOiJodHRwczovL3d3dy5lbXByZXNhLmNvbS9hbGFzdHJpYS9jcmVkZW50aWFscy8zNzM0IiwiaXNzIjoiZGlkOmFsYTpxdW9yOnJlZFQ6OTExN2UzOWQzODcwMTg1OTEwYTYxYWYzYzcwN2Y2MzMzMTA0ZmYxNCIsImF1ZCI6ImRpZDphbGE6cXVvcjpyZWRUOjAwZjQ3MWM3NWMxNGM5ZWU5YjE2ZTRkNjRmOGFjYjQ3YTdiZjJjNGEiLCJpYXQiOjE1ODgxNjAzNzgsImV4cCI6MTU2Mzc4MzM5MiwibmJmIjoxNTYzNzgyNzkyLCJ2cCI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsImh0dHBzOi8vYWxhc3RyaWEuZ2l0aHViLmlvL2lkZW50aXR5L2NyZWRlbnRpYWxzL3YxIl0sInR5cGUiOlsiVmVyaWZpYWJsZVByZXNlbnRhdGlvbiJdLCJwcm9jVXJsIjoiaHR0cHM6Ly93d3cuZW1wcmVzYS5jb20vYWxhc3RyaWEvYnVzaW5lc3Nwcm9jZXNzLzQ1ODMiLCJwcm9jSGFzaCI6IkgzOThzakhkLi4ua2xkalVZbjQ3NW4iLCJ2ZXJpZmlhYmxlQ3JlZGVudGlhbCI6WyJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpGVXpJMU5rc2lMQ0pyYVdRaU9pSmthV1E2WVd4aE9uRjFiM0k2Y21Wa1ZEb3dNR1kwTnpGak56VmpNVFJqT1dWbE9XSXhObVUwWkRZMFpqaGhZMkkwTjJFM1ltWXlZelJoSW4wLmV5SnFkR2tpT2lKb2RIUndjem92TDNkM2R5NWxiWEJ5WlhOaExtTnZiUzloYkdGemRISnBZUzlqY21Wa1pXNTBhV0ZzY3k4ek56TTBJaXdpYVhOeklqb2laR2xrT21Gc1lUcHhkVzl5T25KbFpGUTZNREJtTkRjeFl6YzFZekUwWXpsbFpUbGlNVFpsTkdRMk5HWTRZV05pTkRkaE4ySm1NbU0wWVNJc0luTjFZaUk2SW1ScFpEcGhiR0U2Y1hWdmNqcHlaV1JVT2preE1UZGxNemxrTXpnM01ERTROVGt4TUdFMk1XRm1NMk0zTURkbU5qTXpNekV3TkdabU1UUWlMQ0pwWVhRaU9qRTFPRGd4TmpBek5qRXNJbVY0Y0NJNk1UVTJNemM0TXpNNU1pd2libUptSWpveE5UWXpOemd5TnpreUxDSjJZeUk2ZXlKQVkyOXVkR1Y0ZENJNkltaDBkSEJ6T2k4dmR6TnBaQzV2Y21jdlpHbGtMM1l4SWl3aWRIbHdaU0k2V3lKV1pYSnBabWxoWW14bFEzSmxaR1Z1ZEdsaGJDSXNJa0ZzWVhOMGNtbGhSWGhoYlhCc1pVTnlaV1JsYm5ScFlXd2lYU3dpWTNKbFpHVnVkR2xoYkZOMVltcGxZM1FpT25zaWJHVjJaV3hQWmtGemMzVnlZVzVqWlNJNkltSmhjMmxqSWl3aVpHNXBYMjUxYldWeWJ5STZJakF3TURBd01EUXhTQ0o5ZlgwLlRBWHFHRHN4U3dPSkI1bkJ6b0lvRlJTdE9GYjRIVEpIM09PdWpjczVOQ3lTanN3YTBtSTBSNXEzYXFxc0I0QTltb25PRUIxVnBIMlR1bEJXNjE1S2NnIl19fQ.pTNJ5FzzVcksBWasSSHWaprQR_4jI7C1xP3ROAQH4A0`



**Resultado test:**

![](https://www.lacometanetwork.com/ficheros/alastria/did/U2-presentations-error-type.png)



## 3 - Conclusiones

Con la librería de pruebas se pueden testear los JSON Objets Presentations del modelo DID Alastria para comprobar que los estamos construyendo correctamente.
