### ISSUE TITLE
U6 - alastriaIdentityCreation

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-JSON-objects#29]
Adaptar los cambios de https://github.com/alastria/alastria-identity-lib/issues/73

El jwk del header debe ser opcional

**Comment by msalitu** [comment]
Eliminar la restricción del numero 1 en el kid, puede ser cualquier entero

**Comment by VictorNS69** [comment]
El campo "kid" en el header se tiene que eliminar.
