### ISSUE TITLE
COVID-2.6 Test Alastria Identity Creation

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-JSON-objects#3]
https://github.com/alastria/alastria-identity/wiki/Actions-and-Objects-Definition#03-alastria-id-creation-aic

**Comment by msalitu** [comment]
Una duda, @VictorNS69 @DaniRumpi el AIC ¿debe ir firmado? Creo que finalmente se indicó que no era necesario firmar el AIC porque ya iba firmada la transacción del create y el AT que contiene. Si esto es así, el test debería recibir el AIC sin firmar

**Comment by VictorNS69** [comment]
AIC va firmado:
![image](https://user-images.githubusercontent.com/10101065/83785711-02c32180-a692-11ea-99c0-6764c8a495ad.png)
Dentro, el AT va firmado (una única vez, que hace mucho tiempo, el wallet lo firmaba 2 veces)
![image](https://user-images.githubusercontent.com/10101065/83785811-26866780-a692-11ea-86a6-a45462464238.png)

_Obviar que falta un "0x" en la clave pública, que es un ejemplo antiguo._
