### ISSUE TITLE
COVID-2.5 Test Alastria Session

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-JSON-objects#4]
https://github.com/alastria/alastria-identity/wiki/Actions-and-Objects-Definition#02-alastria-session-as

**Comment by Saithan16** [comment]
La etiqueta "exp" y "iat" no aparecen en la documentación de la wiki, a que corresponden?
El valor de "jti" sigue algún formato especial?

**Comment by VictorNS69** [comment]
> La etiqueta "exp" y "iat" no aparecen en la documentación de la wiki, a que corresponden?
> El valor de "jti" sigue algún formato especial?

- **iat**: IssueAt. Issuance date of the AT.
- **exp**: ExpirationTime. The Expiration time of the AT.

No aparece en ese caso, pero si en otros ejemplos, ya que son etiquetas que se repiten en varios objetos

El campo **jti** es un identificador, así que supongo que tendrá formato string, pero no sé si de alguna manera especifica.

**Comment by Saithan16** [comment]
> * **iat**: IssueAt. Issuance date of the AT.
> * **exp**: ExpirationTime. The Expiration time of the AT.
> 
> No aparece en ese caso, pero si en otros ejemplos, ya que son etiquetas que se repiten en varios objetos
> 
> El campo **jti** es un identificador, así que supongo que tendrá formato string, pero no sé si de alguna manera especifica.

OK, una cuestión mas, el campo "pku" en el ejemplo que nos pones no tiene '0x' pero en el ejemplo de la wiki si, y hubo discusión en la última reunión sobre si con '0x' o sin '0x' ¿como esperamos este hexadecimal?

**Comment by VictorNS69** [comment]
Con "0x"
