### ISSUE TITLE
COVID-2.4 Test Alastria Token

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-JSON-objects#5]
https://github.com/alastria/alastria-identity/wiki/Actions-and-Objects-Definition#01-alastria-token-at

**Comment by nmanero** [comment]
The token example has 3 parts and an invalid signature in jwt.io. is it ok?

**Comment by nmanero** [comment]
Which are the valid values for 'ani' property?

**Comment by VictorNS69** [comment]
> Which are the valid values for 'ani' property?

At the moment it can only be "redt" or "redb" I think, but in the future it will be more
