### ISSUE TITLE
Add new validation fields in the Alastria Tokens

### ISSUE THREAD

**Issue by VictorNS69** [alastria/alastria-identity-JSON-objects#59]
Once https://github.com/alastria/alastria-identity-lib/issues/185 is done, modify the Alastria Token validation so we also check this news attributes.

Also remove the validation from **field "ani"**.

**Comment by VictorNS69** [comment]
Blocked by the Architecture team. 

As soon as it is well defined, we will unlock it.

**Comment by rober12** [comment]
Done
