### ISSUE TITLE
COVID-2.3 Test Presentation Requests

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-JSON-objects#6]
https://github.com/alastria/alastria-identity/wiki/Alastria-DID-Method-Specification-(Quorum-version)#5-presentation-request

**Comment by amoral-eurogestion** [comment]
Buenas, ya he completado los tests y la verificación sobre los hexadecimales. He seguido cómo ejemplo los otros commits.
Pero cuando ejecuto el comando 'tsc' dentro de la carpeta, tal cómo indica la guía, se despliega el manual.
Además si intento hacer el 'node plugfest-alastria.spec.js' me indica el error 'TypeError: describe is not a function'.
¿Alguna idea de que puede estar pasando?, he instalado el Node y el TypeScript, y uso Win10.
