### ISSUE TITLE
Create validation for AlastriaIdentityRecovery (AIR)

### ISSUE THREAD

**Issue by VictorNS69** [alastria/alastria-identity-JSON-objects#60]
We need to add a validation for the new JWT object in the lib.

The object must have the following format: https://github.com/alastria/alastria-identity/wiki/Artifacts-and-User-Stories-Definitions#04-alastria-identity-recovery-air

**Note that at the moment, the Smart Contracts don't implement the "recover Alastria Identity" functionality.**

**This is blocked by https://github.com/alastria/alastria-identity-lib/issues/150**

**Comment by rober12** [comment]
This Alastria Artifact is no longer required.
